### ISSUE TITLE
GPLv3 License

### ISSUE THREAD

**Issue by bcoe** [bguiz/task-yargs#1]
Would you consider changing the license for task-yargs to ISC, or MIT? I can't use GPL licenses at work, so I won't be able to play with task-args as much as I would like to.

**Comment by bguiz** [comment]
Unfortunately, I am quite the fan of GPL over other other open source licences - see all my other repositories on github! My stance on projects using the MIT licence is that I will contribute patches to them, and use them as dependencies. Anything that I maintain myself, on the other hand, will be GPL.

The basic idea, for me at least, is that if I write open source software, other software which uses my open source software should itself be open source as well; if only to maintain the incentive to make their software open source too. If that is not an option, the recourse of obtaining a dual licence is always possible. My intent is pretty much to say **not** a "_no_, you cannot use it in your closed source software", and **instead** a "_yes_, you can use it in your closed source software, subject to a disincetive - so take your pick between the disincentive or open sourcing your software!".

**Comment by bcoe** [comment]
@bguiz totally understand :) 

Just thought I'd ask, since I need to be really careful about not bringing GPLs into my day-job -- doesn't mean I can't contribute and play with the library.

**Comment by bguiz** [comment]
Thanks for understanding!
